### ISSUE TITLE
Investigate: Users receive no data in first span IDs

### ISSUE THREAD

**Issue by nadinevehling** [grafana/explore-traces#141]
Trace View for the first span IDs only showed data after a second attempt. --> [Dovetail watch at 15:00](https://grafana.dovetail.com/data/7uBwle2J1yiFmBD3O7nSy0)

1. User is selecting a span ID.
![Image](https://github.com/user-attachments/assets/df535b9b-e236-42d4-83d5-c429d9cb199d)
2. Selecting for the 2nd time, the Trace visualization shows data.
![Image](https://github.com/user-attachments/assets/8bc69082-8b81-41f6-af82-c46608d508cb)

Additionally, users received no data after selecting the Logs button from Trace list. --> [Dovetail watch at 16:27](https://grafana.dovetail.com/data/7uBwle2J1yiFmBD3O7nSy0)
The time range is too narrow or links are not populated correctly. We should investigate this and tell users what's going on.

**Comment by ifrost** [comment]
Closing the issue:

> 1. Selecting a trace from the list doesn't show the trace view. I wasn't able to reproduce it though it's possible it was related to https://github.com/grafana/explore-traces/issues/110 which was fixed in meantime.

This seems to be fixed.

> 2. Going from Traces to Logs doesn't show any results because the time range is very narrow (same from/to values). This requires changing "Trace to logs" configuration for given data source which by default doesn't expand the time range (...)

Follow-up: https://github.com/grafana/grafana/issues/93794
