### ISSUE TITLE
The structural tab "Apply Full Traces" filter has unexpected behavior

### ISSUE THREAD

**Issue by joe-elliott** [grafana/explore-traces#190]
If the structural tab reveals no data then it shows a button to "apply full traces" filter:

![Image](https://github.com/user-attachments/assets/41a823f6-2cb0-4c8f-b9ce-ac890a351ff4)

Upon clicking this the primary signal is changed from whatever it is to "Full Traces" and the other filters are left alone:

![Image](https://github.com/user-attachments/assets/fc24dafc-d999-45e4-9961-f15dcb254850)

However the other filters could quite easily not apply to "full traces" leaving the entire app w/o data:

![Image](https://github.com/user-attachments/assets/9363951f-1097-42a8-98fb-d08bacb790ac)

I think the simplest solution would be just to remove the "Apply Full Traces" button.

**Comment by joey-grafana** [comment]
Completed in https://github.com/grafana/explore-traces/pull/263
