### ISSUE TITLE
Structural tab shows "No data" warning while streaming

### ISSUE THREAD

**Issue by joe-elliott** [grafana/explore-traces#192]
When streaming the structural tab will now nicely render partial results, but before the first result comes in it shows an erroneous "No data" warning for a second or two.

![Image](https://github.com/user-attachments/assets/171469ed-2a19-469a-b391-3e9c4e4a5f02)

and then

![Image](https://github.com/user-attachments/assets/089c0a5a-d583-465a-a45e-a62b920ebe3f)

**Comment by joey-grafana** [comment]
Completed in https://github.com/grafana/explore-traces/pull/243
