### ISSUE TITLE
"All traces" becomes "Nested set parent < 0" when navigating away from then back to Explore Traces app

### ISSUE THREAD

**Issue by 09jvilla** [grafana/explore-traces#198]
Saw some odd behavior in the selector at the top of the "Explore Traces" app which lets you switch between "server spans"/"consumer spans"/"database calls"/"full traces"/"all spans". Namely when I click back to "Explore > Traces", I seem to replace the selector between all those options with just a hardcoded "where `nestedsetParent < 0` expression". If I delete that expression, then I no longer have a way to choose among the "server spans"/"consumer spans"/"database calls"/"full traces"/"all spans" options. 

See attached video for a demo of the bug. I am able to reset the state by just clicking into another part of Grafana (e.g. Explore Metrics) and then coming back to Explore Traces, so I'd say low priority. 

https://github.com/user-attachments/assets/e90c9cc5-d6d7-488c-b1ce-714b9a2dd717

**Comment by joey-grafana** [comment]
@09jvilla had a look around and could not reproduce. I definitely saw this a few times but it's possible this has been fixed by other changes.

**Comment by 09jvilla** [comment]
Got it - thanks for taking a look! I also tried to reproduce today in the obstraces dev environment and could not. Let's close for now and we can re-open if I see it pop up again.
