### ISSUE TITLE
Cleanup empty data

### ISSUE THREAD

**Issue by joe-elliott** [grafana/explore-traces#207]
If the user applies filters that remove all data the explore traces app could be cleaned up:

![Image](https://github.com/user-attachments/assets/6cbbbd55-dde3-4d8a-9a4a-641840898480)

Perhaps we could just remove the grots from the three upper panels (red rectangle) and only show the one at the bottom (blue rectangle)? Additionally some basic text suggesting they remove filters to see data may be helpful.

**Comment by joey-grafana** [comment]
Completed in https://github.com/grafana/explore-traces/pull/263
