### ISSUE TITLE
Service search does not support capital letters

### ISSUE THREAD

**Issue by tskarhed** [grafana/explore-traces#250]
In my example for the ops instance:

Searching for `Hosted` gives me no results, although one of them actually has a capital letter.

Searching for `hosted` gives me results.

**Comment by grafakus** [comment]
Hi @tskarhed, thank you for reporting!

I'm not super familiar with the app... Did you experience the issue in the search input in the "Breakdown" tab:

![Image](https://github.com/user-attachments/assets/a05d2cc7-8117-45af-81ef-01a3fd8d981c)

Is my understanding correct?

**Comment by grafakus** [comment]
PR to fix it: https://github.com/grafana/explore-traces/pull/252
