### ISSUE TITLE
Improve wording on RED metrics

### ISSUE THREAD

**Issue by nadinevehling** [grafana/explore-traces#90]
Recurring user feedback: "It says to select a metric but the metric is rate? Rate of what?"

We received feedback that it's not obvious how RED metrics belong to traces. Next to the challenge that users oversee the filter bar, we can possibly clarify this selection by improving the wording by mentioning it's an aggregation for example. 
"It says to select a metric but the metric is rate? Rate of what?"

<img width="1533" alt="Screenshot 2024-07-15 at 16 27 01" src="https://github.com/user-attachments/assets/8902188e-b4ab-40e8-bfe5-b61759e28228">

**Comment by joey-grafana** [comment]
This is now covered in the tooltip

![Image](https://github.com/user-attachments/assets/08e39fb1-6001-434f-97c5-033134695598)
